services:
  web:
    build: 
      context: ${PWD}/.docker/httpd/
      dockerfile: ${PWD}/.docker/httpd/Dockerfile
    ports:
      - '8080:80'
    networks:
      - dgapp

  api:
    image: gibbs/api.dangibbs.uk:1.0.1
    volumes:
      - ${PWD}/.docker/database.sqlite:/var/www/html/database/database.sqlite:rw
      - ${PWD}/.docker/.env:/var/www/html/.env
    ports:
      - '9000:9000'
    networks:
      - dgapp

  godan:
    image: gibbs/godanuk:0.5.5
    networks:
      - dgapp

  search:
    image: getmeili/meilisearch:v1.14.0
    ports:
      - '7700:7700'
    env_file:
      - ${PWD}/.docker/.env
    volumes:
      - ${PWD}/.docker/meilisearch/search:/meili_data
    networks:
      - dgapp

  cloudflare-api-proxy:
    build:
      context: ${PWD}/.docker/cloudflare/
      dockerfile: ${PWD}/.docker/cloudflare/Dockerfile
    ports:
      - "8787:8787"
    volumes:
      - ./.docker/cloudflare/src:/app
      - ./.docker/.env:/app/.dev.vars
      - /app/node_modules
    env_file:
      - ${PWD}/.docker/.env
    depends_on:
      - api
    networks:
      - dgapp

networks:
  dgapp:
    driver: bridge
