LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so

<VirtualHost *:80>
	DocumentRoot /usr/local/apache2/htdocs
	ProxyPassMatch ^(.*)$ fcgi://app:9000/var/www/html/public/index.php/$1

	<Directory /usr/local/apache2/htdocs>
			Options Indexes FollowSymLinks MultiViews
			AllowOverride All
	</Directory>
</VirtualHost>
