LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so
LoadModule rewrite_module modules/mod_rewrite.so
LoadModule env_module modules/mod_env.so

<VirtualHost *:80>
	DocumentRoot /usr/local/apache2/htdocs
	ProxyPassMatch ^(.*)$ fcgi://api:9000/var/www/html/public/index.php/$1

	RewriteEngine On
	RewriteCond %{HTTP:Authorization} .
	RewriteRule ^ - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

	<Directory /usr/local/apache2/htdocs>
			Options Indexes FollowSymLinks MultiViews
			AllowOverride All
	</Directory>
</VirtualHost>
