export const transformContent = (content: string, type: string) => {
	if (['changelog', 'reference'].includes(type)) {
		const replacements = [
			// Relegate headings
			{
				search: /^(#{1,4})( .*)/gm,
				content: '$1##$2',
			},
			// Remove strings
			{
				search:
					/All notable changes to this project will be documented in this file. The format is based on \[Keep a Changelog\]\(http\:\/\/keepachangelog\.com\/en\/1\.0\.0\/\) and this project adheres to \[Semantic Versioning\]\(http\:\/\/semver\.org\)\./,
				content: '',
			},
			{
				search:
					/\\\* \_This Changelog was automatically generated by \[github_changelog_generator\]\(https\:\/\/github.com\/github-changelog-generator\/github-changelog-generator\)\_/,
				content: '',
			},
		];

		replacements.forEach((replacement) => {
			content = content.replace(replacement.search, replacement.content);
		});

		return content;
	}

	return content;
};
