// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
	TRelationship extends
		| prismic.CustomTypeModelFetchCustomTypeLevel1
		| prismic.CustomTypeModelFetchCustomTypeLevel2
		| prismic.CustomTypeModelFetchGroupLevel1
		| prismic.CustomTypeModelFetchGroupLevel2,
	TData extends Record<
		string,
		prismic.AnyRegularField | prismic.GroupField | prismic.NestedGroupField | prismic.SliceZone
	>,
	TLang extends string,
> =
	// Content relationship fields
	{
		[TSubRelationship in Extract<
			TRelationship['fields'][number],
			prismic.CustomTypeModelFetchContentRelationshipLevel1
		> as TSubRelationship['id']]: ContentRelationshipFieldWithData<
			TSubRelationship['customtypes'],
			TLang
		>;
	} & {
		// Group
		[TGroup in Extract<
			TRelationship['fields'][number],
			prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2
		> as TGroup['id']]: TData[TGroup['id']] extends prismic.GroupField<infer TGroupData>
			? prismic.GroupField<PickContentRelationshipFieldData<TGroup, TGroupData, TLang>>
			: never;
	} & {
		// Other fields
		[TFieldKey in Extract<TRelationship['fields'][number], string>]: TFieldKey extends keyof TData
			? TData[TFieldKey]
			: never;
	};

type ContentRelationshipFieldWithData<
	TCustomType extends
		| readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
		| readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
	TLang extends string = string,
> = {
	[ID in Exclude<TCustomType[number], string>['id']]: prismic.ContentRelationshipField<
		ID,
		TLang,
		PickContentRelationshipFieldData<
			Extract<TCustomType[number], { id: ID }>,
			Extract<prismic.Content.AllDocumentTypes, { type: ID }>['data'],
			TLang
		>
	>;
}[Exclude<TCustomType[number], string>['id']];

type BlogDocumentDataSlicesSlice =
	| ButtonGroupSlice
	| BadgesSlice
	| ImageSlice
	| TabsSlice
	| MarkdownSlice
	| FileRendererSlice
	| AlertSlice;

/**
 * Content for Blog documents
 */
interface BlogDocumentData {
	/**
	 * Title field in *Blog*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * Summary field in *Blog*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog.summary
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	summary: prismic.KeyTextField;

	/**
	 * Date field in *Blog*
	 *
	 * - **Field Type**: Timestamp
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog.date
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/timestamp
	 */
	date: prismic.TimestampField;

	/**
	 * Slice Zone field in *Blog*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<BlogDocumentDataSlicesSlice>; /**
	 * Meta Title field in *Blog*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: blog.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Blog*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: blog.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Blog*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;

	/**
	 * LinkData field in *Blog*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: JSON Link Data
	 * - **API ID Path**: blog.linkdata
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	linkdata: prismic.RichTextField;
}

/**
 * Blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<BlogDocumentData>,
	'blog',
	Lang
>;

type ProjectDocumentDataSlicesSlice =
	| ImageSlice
	| TabsSlice
	| AlertSlice
	| FileRendererSlice
	| BadgesSlice
	| ButtonGroupSlice
	| MarkdownSlice;

type ProjectDocumentDataSlices1Slice = never;

/**
 * Content for Project documents
 */
interface ProjectDocumentData {
	/**
	 * Title field in *Project*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: The title to display
	 * - **API ID Path**: project.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * Summary field in *Project*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: The summary to display
	 * - **API ID Path**: project.summary
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	summary: prismic.KeyTextField;

	/**
	 * Date field in *Project*
	 *
	 * - **Field Type**: Timestamp
	 * - **Placeholder**: The original publication date
	 * - **API ID Path**: project.date
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/timestamp
	 */
	date: prismic.TimestampField;

	/**
	 * Slice Zone field in *Project*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<ProjectDocumentDataSlicesSlice>; /**
	 * Meta Title field in *Project*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: project.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Project*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: project.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Project*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;

	/**
	 * LinkData field in *Project*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: JSON Link Data
	 * - **API ID Path**: project.linkdata
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	linkdata: prismic.RichTextField;

	/**
	 * Slice Zone field in *Project*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.slices1[]
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices1: prismic.SliceZone<ProjectDocumentDataSlices1Slice>;
}

/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<ProjectDocumentData>,
	'project',
	Lang
>;

type RecipeDocumentDataSlicesSlice = never;

/**
 * Content for Recipe documents
 */
interface RecipeDocumentData {
	/**
	 * Slice Zone field in *Recipe*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: recipe.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<RecipeDocumentDataSlicesSlice>; /**
	 * Meta Title field in *Recipe*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: recipe.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Recipe*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: recipe.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Recipe*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: recipe.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;

	/**
	 * LinkData field in *Recipe*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: recipe.linkdata
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	linkdata: prismic.RichTextField;
}

/**
 * Recipe document from Prismic
 *
 * - **API ID**: `recipe`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RecipeDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<RecipeDocumentData>,
	'recipe',
	Lang
>;

type ToolsDocumentDataSlicesSlice =
	| ImageSlice
	| MarkdownSlice
	| AlertSlice
	| TabsSlice
	| BadgesSlice
	| ButtonGroupSlice
	| FileRendererSlice;

/**
 * Content for Tools documents
 */
interface ToolsDocumentData {
	/**
	 * Title field in *Tools*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: tools.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * Summary field in *Tools*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: tools.summary
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	summary: prismic.KeyTextField;

	/**
	 * Date field in *Tools*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: tools.date
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/date
	 */
	date: prismic.DateField;

	/**
	 * Slice Zone field in *Tools*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: tools.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<ToolsDocumentDataSlicesSlice>; /**
	 * Meta Title field in *Tools*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: tools.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Tools*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: tools.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Tools*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: tools.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;

	/**
	 * LinkData field in *Tools*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: JSON Link Data
	 * - **API ID Path**: tools.linkdata
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	linkdata: prismic.RichTextField;
}

/**
 * Tools document from Prismic
 *
 * - **API ID**: `tools`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ToolsDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<ToolsDocumentData>,
	'tools',
	Lang
>;

export type AllDocumentTypes = BlogDocument | ProjectDocument | RecipeDocument | ToolsDocument;

/**
 * Primary content in *Alert → Default → Primary*
 */
export interface AlertSliceDefaultPrimary {
	/**
	 * Type field in *Alert → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: success
	 * - **API ID Path**: alert.default.primary.type
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	type: prismic.SelectField<
		'success' | 'danger' | 'warning' | 'info' | 'primary' | 'secondary',
		'filled'
	>;

	/**
	 * Message field in *Alert → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: The alert message
	 * - **API ID Path**: alert.default.primary.message
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	message: prismic.RichTextField;
}

/**
 * Default variation for Alert Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AlertSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<AlertSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Alert*
 */
type AlertSliceVariation = AlertSliceDefault;

/**
 * Alert Shared Slice
 *
 * - **API ID**: `alert`
 * - **Description**: Alert
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AlertSlice = prismic.SharedSlice<'alert', AlertSliceVariation>;

/**
 * Item in *Badges → Default → Primary → Badge*
 */
export interface BadgesSliceDefaultPrimaryBadgeItem {
	/**
	 * URL field in *Badges → Default → Primary → Badge*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: The image alt text
	 * - **API ID Path**: badges.default.primary.badge[].url
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Source field in *Badges → Default → Primary → Badge*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: The badge image src
	 * - **API ID Path**: badges.default.primary.badge[].src
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	src: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Badges → Default → Primary*
 */
export interface BadgesSliceDefaultPrimary {
	/**
	 * Badge field in *Badges → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: badges.default.primary.badge[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	badge: prismic.GroupField<Simplify<BadgesSliceDefaultPrimaryBadgeItem>>;
}

/**
 * Default variation for Badges Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BadgesSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<BadgesSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Badges*
 */
type BadgesSliceVariation = BadgesSliceDefault;

/**
 * Badges Shared Slice
 *
 * - **API ID**: `badges`
 * - **Description**: Badges
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BadgesSlice = prismic.SharedSlice<'badges', BadgesSliceVariation>;

/**
 * Item in *ButtonGroup → Default → Primary → Button*
 */
export interface ButtonGroupSliceDefaultPrimaryButtonItem {
	/**
	 * Link field in *ButtonGroup → Default → Primary → Button*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: button_group.default.primary.button[].link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<
		string,
		string,
		unknown,
		prismic.FieldState,
		'GitHub' | 'Docker Hub' | 'Puppet Forge'
	>;
}

/**
 * Primary content in *ButtonGroup → Default → Primary*
 */
export interface ButtonGroupSliceDefaultPrimary {
	/**
	 * Button field in *ButtonGroup → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: button_group.default.primary.button[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	button: prismic.GroupField<Simplify<ButtonGroupSliceDefaultPrimaryButtonItem>>;
}

/**
 * Default variation for ButtonGroup Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ButtonGroupSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ButtonGroupSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *ButtonGroup*
 */
type ButtonGroupSliceVariation = ButtonGroupSliceDefault;

/**
 * ButtonGroup Shared Slice
 *
 * - **API ID**: `button_group`
 * - **Description**: ButtonGroup
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ButtonGroupSlice = prismic.SharedSlice<'button_group', ButtonGroupSliceVariation>;

/**
 * Primary content in *FileRenderer → Default → Primary*
 */
export interface FileRendererSliceDefaultPrimary {
	/**
	 * Path field in *FileRenderer → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Path relative to src/assets/files/
	 * - **API ID Path**: file_renderer.default.primary.path
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	path: prismic.KeyTextField;

	/**
	 * Type field in *FileRenderer → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: Markdown
	 * - **API ID Path**: file_renderer.default.primary.type
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	type: prismic.SelectField<'Markdown' | 'Code', 'filled'>;

	/**
	 * Extra field in *FileRenderer → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: file_renderer.default.primary.extra
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	extra: prismic.KeyTextField;
}

/**
 * Default variation for FileRenderer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FileRendererSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<FileRendererSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *FileRenderer*
 */
type FileRendererSliceVariation = FileRendererSliceDefault;

/**
 * FileRenderer Shared Slice
 *
 * - **API ID**: `file_renderer`
 * - **Description**: FileRenderer
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FileRendererSlice = prismic.SharedSlice<'file_renderer', FileRendererSliceVariation>;

/**
 * Primary content in *Image → Default → Primary*
 */
export interface ImageSliceDefaultPrimary {
	/**
	 * Image field in *Image → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ImageSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation = ImageSliceDefault;

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageSlice = prismic.SharedSlice<'image', ImageSliceVariation>;

/**
 * Primary content in *Markdown → Default → Primary*
 */
export interface MarkdownSliceDefaultPrimary {
	/**
	 * Content field in *Markdown → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: markdown.default.primary.content
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField;
}

/**
 * Default variation for Markdown Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MarkdownSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<MarkdownSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Markdown*
 */
type MarkdownSliceVariation = MarkdownSliceDefault;

/**
 * Markdown Shared Slice
 *
 * - **API ID**: `markdown`
 * - **Description**: Markdown
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MarkdownSlice = prismic.SharedSlice<'markdown', MarkdownSliceVariation>;

/**
 * Item in *Tabs → Default → Primary → Tabs*
 */
export interface TabsSliceDefaultPrimaryTabsItem {
	/**
	 * Title field in *Tabs → Default → Primary → Tabs*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: tabs.default.primary.tabs[].title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * Type field in *Tabs → Default → Primary → Tabs*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: Markdown
	 * - **API ID Path**: tabs.default.primary.tabs[].type
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	type: prismic.SelectField<'Markdown' | 'YAML', 'filled'>;

	/**
	 * Content field in *Tabs → Default → Primary → Tabs*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: tabs.default.primary.tabs[].content
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField;
}

/**
 * Item in *Tabs → Tabs with Files → Primary → Files*
 */
export interface TabsSliceTabsWithFilesPrimaryFilesItem {
	/**
	 * Title field in *Tabs → Tabs with Files → Primary → Files*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: tabs.tabsWithFiles.primary.files[].title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * Path field in *Tabs → Tabs with Files → Primary → Files*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: tabs.tabsWithFiles.primary.files[].path
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	path: prismic.KeyTextField;

	/**
	 * Type field in *Tabs → Tabs with Files → Primary → Files*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: Markdown
	 * - **API ID Path**: tabs.tabsWithFiles.primary.files[].type
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	type: prismic.SelectField<'Markdown' | 'YAML', 'filled'>;
}

/**
 * Primary content in *Tabs → Default → Primary*
 */
export interface TabsSliceDefaultPrimary {
	/**
	 * Title field in *Tabs → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: tabs.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * Direction field in *Tabs → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: Horizontal
	 * - **API ID Path**: tabs.default.primary.direction
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	direction: prismic.SelectField<'Horizontal' | 'Vertical', 'filled'>;

	/**
	 * Content field in *Tabs → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: tabs.default.primary.content
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField;

	/**
	 * Tabs field in *Tabs → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: tabs.default.primary.tabs[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	tabs: prismic.GroupField<Simplify<TabsSliceDefaultPrimaryTabsItem>>;
}

/**
 * Default variation for Tabs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TabsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<TabsSliceDefaultPrimary>,
	never
>;

/**
 * Primary content in *Tabs → Tabs with Files → Primary*
 */
export interface TabsSliceTabsWithFilesPrimary {
	/**
	 * Title field in *Tabs → Tabs with Files → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: tabs.tabsWithFiles.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * Direction field in *Tabs → Tabs with Files → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: Horizontal
	 * - **API ID Path**: tabs.tabsWithFiles.primary.direction
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	direction: prismic.SelectField<'Horizontal' | 'Vertical', 'filled'>;

	/**
	 * Content field in *Tabs → Tabs with Files → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: tabs.tabsWithFiles.primary.content
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField;

	/**
	 * Files field in *Tabs → Tabs with Files → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: tabs.tabsWithFiles.primary.files[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	files: prismic.GroupField<Simplify<TabsSliceTabsWithFilesPrimaryFilesItem>>;
}

/**
 * Tabs with Files variation for Tabs Slice
 *
 * - **API ID**: `tabsWithFiles`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TabsSliceTabsWithFiles = prismic.SharedSliceVariation<
	'tabsWithFiles',
	Simplify<TabsSliceTabsWithFilesPrimary>,
	never
>;

/**
 * Slice variation for *Tabs*
 */
type TabsSliceVariation = TabsSliceDefault | TabsSliceTabsWithFiles;

/**
 * Tabs Shared Slice
 *
 * - **API ID**: `tabs`
 * - **Description**: Tabs
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TabsSlice = prismic.SharedSlice<'tabs', TabsSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig,
		): prismic.Client<AllDocumentTypes>;
	}

	interface CreateWriteClient {
		(
			repositoryNameOrEndpoint: string,
			options: prismic.WriteClientConfig,
		): prismic.WriteClient<AllDocumentTypes>;
	}

	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			BlogDocument,
			BlogDocumentData,
			BlogDocumentDataSlicesSlice,
			ProjectDocument,
			ProjectDocumentData,
			ProjectDocumentDataSlicesSlice,
			ProjectDocumentDataSlices1Slice,
			RecipeDocument,
			RecipeDocumentData,
			RecipeDocumentDataSlicesSlice,
			ToolsDocument,
			ToolsDocumentData,
			ToolsDocumentDataSlicesSlice,
			AllDocumentTypes,
			AlertSlice,
			AlertSliceDefaultPrimary,
			AlertSliceVariation,
			AlertSliceDefault,
			BadgesSlice,
			BadgesSliceDefaultPrimaryBadgeItem,
			BadgesSliceDefaultPrimary,
			BadgesSliceVariation,
			BadgesSliceDefault,
			ButtonGroupSlice,
			ButtonGroupSliceDefaultPrimaryButtonItem,
			ButtonGroupSliceDefaultPrimary,
			ButtonGroupSliceVariation,
			ButtonGroupSliceDefault,
			FileRendererSlice,
			FileRendererSliceDefaultPrimary,
			FileRendererSliceVariation,
			FileRendererSliceDefault,
			ImageSlice,
			ImageSliceDefaultPrimary,
			ImageSliceVariation,
			ImageSliceDefault,
			MarkdownSlice,
			MarkdownSliceDefaultPrimary,
			MarkdownSliceVariation,
			MarkdownSliceDefault,
			TabsSlice,
			TabsSliceDefaultPrimaryTabsItem,
			TabsSliceDefaultPrimary,
			TabsSliceTabsWithFilesPrimaryFilesItem,
			TabsSliceTabsWithFilesPrimary,
			TabsSliceVariation,
			TabsSliceDefault,
			TabsSliceTabsWithFiles,
		};
	}
}
