name: Deploy

on:
  push:
    tags:
       - '*'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    environment: production
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Install NPM Dependencies
        run: npm ci 
      - name: Build
        run: |
          npm run build
        env:
          APP_SERVICE_URL: ${{ vars.APP_SERVICE_URL }}
          APP_SEARCH_URL: ${{ vars.APP_SEARCH_URL }}
          BASE_URL: ${{ vars.BASE_URL }}
          PRISMIC_REPOSITORY: ${{ secrets.PRISMIC_REPOSITORY }}
          PRISMIC_ACCESS_TOKEN: ${{ secrets.PRISMIC_ACCESS_TOKEN }}
          VITE_APP_SERVICE_URL: ${{ vars.APP_SERVICE_URL }}
          VITE_MODE: production
          VITE_MEILISEARCH_URL: ${{ vars.VITE_MEILISEARCH_URL }}
          VITE_MEILISEARCH_INDEX: ${{ vars.VITE_MEILISEARCH_INDEX }}
          VITE_MEILISEARCH_SEARCH_KEY: ${{ vars.VITE_MEILISEARCH_SEARCH_KEY }}
          VITE_MEILISEARCH_MASTER_KEY: ${{ secrets.VITE_MEILISEARCH_MASTER_KEY }}
      - name: Archive Build
        env:
          INPUT_PATH: dist/
        run: |
          tar \
            --dereference --hard-dereference \
            --directory "$INPUT_PATH" \
            -cvf "$RUNNER_TEMP/build.tar" \
            --exclude=.git \
            --exclude=.github \
            .
      - name: Upload artefact
        uses: actions/upload-artifact@v7
        with:
          name: github-pages
          path: ${{ runner.temp }}/build.tar
          retention-days: '1'

  deploy:
    name: Deploy
    runs-on: ubuntu-24.04
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-page
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
