name: Tests

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run lint

  acceptance:
    name: Acceptance Tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Run server
        run: |
          cp -f .env.development .env
          npm run build
          npm run serve &
          sleep 15
        env:
          APP_ENV: development
          APP_URL: http://localhost:8080/

      - name: Run tests
        run: npm run test:acceptance
        env:
          APP_ENV: development
          APP_URL: http://localhost:8080/

  e2e:
    name: E2E Tests
    runs-on: ubuntu-20.04
    container: genv/webdriver-chromium:latest
    services:
      app:
        image: gibbs/app.dangibbs.uk:latest
      godanuk:
        image: gibbs/godanuk:latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install
        env:
          CHROMEDRIVER_FILEPATH: /usr/bin/chromedriver
          CHROMEDRIVER_SKIP_DOWNLOAD: true

      - name: Run server
        run: |
          cp -f .env.development .env
          npm run build
          npm run serve &
          sleep 15
        env:
          APP_ENV: development
          APP_URL: http://localhost:8080/

      - name: Run tests
        run: npm run test:e2e
        env:
          APP_ENV: testing
          APP_URL: http://localhost:8080/
