name: Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'master'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run lint
      - run: APP_ENV=production APP_URL=https://dangibbs.uk npm run build
      - run: |
          APP_ENV=production APP_URL=https://dangibbs.uk npm run serve &
          sleep 15 &&
          npm run test:acceptance
