name: Tests

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build and Test
        run: |
          cp -f .env.development .env
          npm run build
          npm run serve &
          sleep 15
          npm run test:acceptance
        env:
          APP_ENV: development
          APP_URL: http://localhost:8080/
